[package]
name = "rust"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aligned-vec = "0.5"
hashbrown = "0.14.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
strip = true
